import React, { useEffect } from "react";
import Faq from "react-faq-component";
import { Link, Redirect } from 'react-router-dom';
const data = {
	rows: [
		{
			title: "What is DeFi",
			content: `DeFi stands for Decentralized Finance, meaning that there is no centralized control but the users have total control of their own assets. The open source environment of DeFi allows fast and unrestricted development of applications for digital assets, protocols, smart contracts and dApps built on a blockchain. We believe DeFi is the future for a financial ecosystem independent of centralized institutions, and can potentially revolutionize the way people use their assets.`,
		},
		{
			title: "What is TheToken.Network offering?",
			content:
				"In short, TheToken.Network aims to connect the crypto DeFi world with the “real” world and allow various use cases to bring liquidity providers and demand together. Users can tokenize a large variety of assets and collateralize their assets to a liquidity pool. To get more in depth information, please read our Whitepaper and join us on Discord and Telegram.",
		},
		{
			title: "Why is TTN token more valuable than almost all other crypto token?",
			content: `TTN is always backed by assets, either a stable-coin mix in a liquidity pool and/or tokenized assets provided by users as collateral. Therefore, TTN tokens always hold a quantifiable value in assets.`,
		},
		{
			title: "What makes TTN special?",
			content: "TTN is backed by assets and therefore has a clear quantifiable value but also generates interest from TTNP liquidity pools and gets a percentage of the fee revenue on the platform.Furthermore, TTN holders directly decide about all issues in regards to the platform – from TheToken.Network Foundation team to the liquidity pool strategy.TTN holders own TheToken.Network.",
		},
		{
			title: "What is TheToken.Network Foundation?",
			content: "TheToken.Network Foundation (TTNF) is the team responsible for administrative tasks as well as carrying out the requests of the TTN holders. TTNF makes sure that the platform is operative and develops functionality around the services provided. TTNF holds a predefined amount of TTN token and has to finance its activities out of the passive revenue generated by the Foundation's TTN allocation.",
		},
	],
};
const styles = {
	bgColor: 'transparent',
	titleTextColor: "white",
	rowTitleColor: "white",
	rowContentColor: 'white',
	arrowColor: "white",
};

const config = {
	// animate: true,
	// arrowIcon: "V",
	// tabFocus: true
};
class MainPage extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			mobileMenu  : false,
			redirect : false
		};
	}
	componentWillMount(){
		this.setState({ redirect: true});
		// window.location.assign('/')
	}
	onClickFaq = () =>{
		console.log("as")
		window.scroll({
			top: 600,
			behavior: 'smooth'
		});
	}
	
	render() {
		console.log(this.state.redirect)
		return (
			<div>
				{/* {this.state.redirect && <Redirect to = '/'/>} */}
				<div className="nk-wrap">
					<header className="nk-header page-header is-transparent is-sticky is-dark" id="header">					
						<div className="header-main">
							<div className="header-container container container-xxl">
								<div className="header-wrap container">									
									<div className="header-logo logo">
										<a href="./" className="logo-link">
											<img className="logo-dark" src="/assets/images/logo/logo.png" alt="logo" />
											<img className="logo-light" src="/assets/images/logo/logo.png" alt="logo" />
										</a>
									</div>								
									<div className="header-nav-toggle">
										<a href="#" className="navbar-toggle" data-menu-toggle="header-menu">
											<div className="toggle-line">
												<span></span>
											</div>
										</a>
									</div>									
									<div className="header-navbar">
										<nav className="header-menu" id="header-menu">
											<ul className="menu">											
												<li className="menu-item"><Link  className="menu-link nav-link" to="/swap">BUY TTN</Link></li>
												<li className="menu-item"><a className="menu-link nav-link" style={{cursor: 'pointer'}} onClick={() => this.onClickFaq()}>FAQ</a></li>
											</ul>
										</nav>
									</div>									
								</div>
							</div>
						</div>						
						<div className="header-banner bg-theme-dark" style={{backgroundImage: 'url(assets/images/Header2.png)'}}>
							<div className="nk-banner">
								<div className="banner banner-mask-fix banner-fs banner-single tc-light">
									<div className="banner-wrap">
										<div className="container">
											<div className="row align-items-center justify-content-center gutter-vr-30px">
												<div className="col-lg-8 order-lg-last">
													<div className="banner-gfx banner-gfx-re-s3 animated" data-animate="fadeInUp" data-delay="1.25">
														<h1 className="title title-xl-2 title-semibold animated" style={{ textAlign: 'center', width: '100%', position: 'absolute', top: '45%', zIndex: '99', color: '#e29f3a' }} data-animate="fadeInUp" data-delay="1.35">DAPP</h1>
														<img src="/assets/images/dark/gfx-d-dark.png" alt="header"/>
														<img className="banner-gfx-icon banner-gfx-icon-1" src="/assets/images/icons/icon-custom.png" alt=""/>
														<img className="banner-gfx-icon banner-gfx-icon-2" src="/assets/images/icons/icon-bitcoin.png" alt=""/>
													</div>
												</div>
												<div className="col-lg-4">
													<div className="banner-caption wide-auto text-center text-lg-left">
														<div className="cpn-head mt-0">
															<h1 className="title title-xl-2 title-semibold animated" data-animate="fadeInUp" data-delay="1.35">TheToken.Network Exchange</h1>
														</div>
														<div className="cpn-text cpn-text-s1">
															<p className="lead animated" data-animate="fadeInUp" data-delay="1.45">The Exchange of TheToken.Network allows you to conveniently buy $TTN tokens within seconds.</p>
														</div>
														<div className="cpn-btns">
															<ul className="btn-grp animated" data-animate="fadeInUp" data-delay="1.55">
																<li><a className="btn btn-md btn-grad btn-round" data-delay="1.25" onClick ={()=>this.onClickFaq()}>FAQ</a></li>
																<li><Link to="swap" className="btn btn-md btn-grad btn-grad-alternet btn-round">BUY TTN</Link></li>
															</ul>
																
														</div>
														<div className="cpn">
															<ul className="btn-grp animated" data-animate="fadeInUp" data-delay="1.55">
																<li><a href="https://www.youtube.com/watch?v=SSo_EIwHSd4" className="link link-light link-break video-popup"><em className="icon-circle icon-border icon-animation fas fa-play"></em><span>How it Works</span></a></li>
															</ul>
														</div>
													</div>
												</div>                          
											</div>
										</div>
									</div>
								</div>
								<footer id="faq" className="nk-footer-bar section tc-light" style={{ paddingTop: '0px' }}>
									<div className="container">
										<Faq
											data={data}
											styles={styles}
											config={config}
										/>
									</div>

								</footer>
							</div>
						</div>
					</header>
					
					<div className="nk-ovm nk-ovm-repeat nk-ovm-fixed shape-i">
						<div className="ovm-line"></div>
					</div>
				</div>
				<div className="preloader preloader-alt no-split">
					<span className="spinner spinner-alt">
						<img className="spinner-brand" src="/assets/images/logo/logo.png" alt=""/>
					</span>
				</div>
			</div>
		);
	}
}
export default MainPage;
